# Generated by Django 5.2.10 on 2026-02-02 07:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GlassCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('brand', models.CharField(blank=True, default='', max_length=100)),
                ('note', models.TextField(blank=True, default='')),
                ('photo_filename', models.CharField(blank=True, default='', max_length=255)),
            ],
            options={
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='GlassAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(db_index=True, max_length=255, unique=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='panel.glasscard')),
            ],
            options={
                'ordering': ('query',),
            },
        ),
        migrations.CreateModel(
            name='GlassLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='panel.glasscard')),
            ],
            options={
                'ordering': ('sort_order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='GlassSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=255)),
                ('height', models.DecimalField(db_index=True, decimal_places=2, max_digits=7)),
                ('width', models.DecimalField(db_index=True, decimal_places=2, max_digits=7)),
                ('photo_path', models.CharField(blank=True, default='', max_length=255)),
            ],
            options={
                'indexes': [models.Index(fields=['height', 'width'], name='panel_glass_height_1badcb_idx')],
            },
        ),
    ]
